config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  root 'static_pages#home'

  resources :menus, only: %i(index show) do
    resources :meals, only: %i(index create)
  end

  resources :users, only: [:index, :show] do
    resources :orders, only: :create
  end
end

app/models/meal.rb
class Meal < ActiveRecord::Base
  belongs_to :menu
  has_and_belongs_to_many :orders

  validates :price, numericality: { greater_than_or_equal_to: 0 }
  validates :name, presence: true

  enum course: %i(starter main drink)

  def price
    self[:price] / 100.0
  end

  def price=(value)
    self[:price] = value * 100
  end

  def self.find_by_ids(ids)
    ids.map { |id| find_by(id: id) }
  end
end

app/models/menu.rb
class Menu < ActiveRecord::Base
  has_many :meals
  has_many :orders

  validates :date, uniqueness: true

  scope :for_week, -> (date_in_week = nil) {
    date_in_week = date_in_week || Date.today
    start_of_week = date_in_week.monday
    end_of_week = start_of_week + 4

    where('date >= :start_of_week and date < :end_of_week',
      start_of_week: start_of_week,
      end_of_week: end_of_week)
    .order(:date)
  }

  def orders_total_price
    orders.map(&:total_price).reduce(:+)
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  belongs_to :menu
  has_and_belongs_to_many :meals

  validates :user_id, presence: true
  validates :menu_id, presence: true
  validate :check_meals_uniq, on: :create
  validate :check_meals_presence, on: :create

  def decorated_errors
    errors.messages.map { |field, message| "#{field.capitalize}: #{message.join(', ')}" }.join('. ')
  end

  def user_name
    user&.name
  end

  def total_price
    meals.map(&:price).reduce(:+)
  end

  private

  def check_meals_uniq
    unless meals.to_ary.uniq { |meal| meal.course }.size == meals.size
      errors.add(:meals, 'can be only 1 meal for every course')
    end
  end

  def check_meals_presence
    errors.add(:meals, "can't be empty") if meals.empty?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :rememberable, :validatable

  has_many :orders

  validates :name, presence: true

  after_create :make_admin

  private

  def make_admin
    update_attributes(admin: true) if User.count == 1
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController

  before_filter :sanitize_page_params, only: :create

  def index
    @menu = Menu.find_by(id: params[:menu_id])
    @meals = Meal.where(menu_id: params[:menu_id])
  end

  def create
    meal = Meal.new(meal_params)
    meal.menu_id = params[:menu_id]
    meal.save
    redirect_to menu_meals_path
  end

  private

  def meal_params
    params.require(:meal).permit(:name, :course, :price)
  end

  def sanitize_page_params
    params[:meal][:price] = params[:meal][:price].to_f
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :authenticate_user!

  def index
    @menus = Menu.for_week
  end

  def show
    @menu = Menu.find(params[:id])
    @meals = @menu.meals
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!

  def create
    meals = Meal.find_by_ids(params[:meals])
    params_for_create = order_params
    params_for_create[:meals] = meals
    order = Order.new(params_for_create)
    if order.valid?
      order.save
      redirect_to menu_meals_path(order_params[:menu_id]), notice: 'Your order is processed'
    else
      redirect_to menu_meals_path(order_params[:menu_id]), alert: "#{order.decorated_errors}"
    end
  end

  private

  def order_params
    params.permit(:user_id, :menu_id, :meals)
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
    # super
  # end

  # POST /resource
  # def create
    # super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
    # super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_filter do
    redirect_to new_user_session_path unless current_user && current_user.admin?
  end

  def index
    @users = User.order(:id).all[1..-1] # except admin user
  end

  def show
    @user = User.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
  def decorate(menu)
    link_to "#{menu.date.strftime('%A')} (#{menu.date.strftime('%d.%m.%Y')})", menu_meals_path(menu)
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.haml
.container
  %nav.navbar.navbar-default
    .container-fluid
      .navbar-header
        %a.navbar-brand{ href: '#'} OrderYourLunch
        - if user_signed_in?
          %ul.nav.navbar-nav
            %li= link_to 'Dashboard', menus_path
            -if current_user.admin?
              %li= link_to 'Users', users_path
      .collapse.navbar-collapse#bs-example-navbar-collapse-1
        %ul.nav.navbar-nav.navbar-right
          - if user_signed_in?
            %li= link_to 'Edit my profile', edit_user_registration_path
            %li= link_to 'Sign Out', destroy_user_session_path, method: :delete
          - else
            %li= link_to 'Sign In', new_user_session_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title OrderYourLunch
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/header'
    .container
      - flash.each do |key, value|
        - alert_key = key == 'alert' ? 'danger' : 'success'
        = content_tag(:div, value, class: "alert alert-#{alert_key}")
      = yield

app/views/meals/_add_meal_form.html.haml
%h2 Add meal
= simple_form_for(Meal.new, as: Meal.new, url: menu_meals_path) do |f|
  = f.error_notification
  .form-inputs
    = f.input :name, required: true, autofocus: true
    = f.input :course, collection: %w(starter main drink), required: true
    = f.input :price, required: true, as: :float
    = f.button :submit, 'Add meal'

app/views/meals/index.html.haml
%table.table.table-hover#meals
  - @meals.each do |meal|
    %tbody
      %tr.clickable-row
        %td{style: 'display: none;'}= meal.id
        %td= meal.name
        %td= meal.course
        %td= meal.price

- if current_user.admin? && @menu.date.today?
  = render 'add_meal_form'
- else
  = link_to 'Submit',
            user_orders_path(current_user, menu_id: params[:menu_id]),
            id: 'submit',
            class: 'btn btn-primary',
            method: :post

%script{type: 'text/javascript',
        src: '/javascripts/meals.js'}

app/views/menus/index.html.haml
- @menus.each do |menu|
  %h2= decorate(menu)
  - if current_user.admin?
    %table.table.table-hover#orders
      - menu.orders.each do |order|
        %tbody
          %tr
            %td= order.user_name
            %td= order.meals.map { |meal| "#{meal.name}(#{meal.course}) #{meal.price}" }.join(', ')
    %p= "Total: #{menu.orders_total_price}"

app/views/users/index.html.haml
%ul
  - @users.each do |user|
    %li
      = link_to user.name, user_path(user)

app/views/users/shared/_links.html.haml
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  %br/
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider)
    %br/

app/views/users/show.html.haml
%p= @user.name
%p= @user.email